#Configuation for robot odometry EKF
#
frequency: 50
two_d_mode: true

odom0: /dingo_velocity_controller/odom
# TODO: how to fill this in properly? (currently matches ridgeback)
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 4 # TODO: needed?

imu0: /imu/data
# TODO: how to fill this in properly? (currently matches ridgeback)
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              true, true, false]
imu0_differential: false  # TODO: true? (false for ridgeback)
imu0_queue_size: 4 # TODO: needed?

odom_frame: odom
base_link_frame: base_link
world_frame: odom
